export const colors = {
  bg: "#F7F9FA",
  surface: "#FFFFFF",
  surfaceSubtle: "#F4F7F8",
  text: "#11181C",
  textSecondary: "#69757D",
  textTertiary: "#929CA2",
  border: "#E4E9EC",
  borderStrong: "#D5DDE1",
  cyan: "#10B9CE",
  cyanStrong: "#078EA4",
  cyanSoft: "#EAF9FC",
  orange: "#FF6B35",
  orangeStrong: "#D94D1C",
  orangeSoft: "#FFF1EB",
  danger: "#D9363E",
  success: "#087A67",

  // Transitional aliases keep existing secondary screens stable while the main vote flow moves first.
  ink: "#11181C",
  panel: "#FFFFFF",
  panelSoft: "#F4F7F8",
  paper: "#FFFFFF",
  muted: "#69757D",
  line: "#E4E9EC",
  accent: "#FF6B35",
} as const;
