export type CommentErrorCode =
  | "INVALID_CURSOR"
  | "VOTE_REQUIRED"
  | "COMMENTS_UNAVAILABLE"
  | "SESSION_REQUIRED"
  | "COMMENT_ALREADY_EXISTS"
  | "REPLY_PARENT_UNAVAILABLE"
  | "COMMENT_NOT_FOUND"
  | "COMMENT_AUTHOR_REQUIRED"
  | "COMMENT_MUTATION_UNAVAILABLE"
  | "IDEMPOTENCY_CONFLICT"
  | "IDEMPOTENCY_INCOMPLETE"
  | "COMMENT_TOO_SHORT"
  | "COMMENT_TOO_LONG"
  | "COMMENT_URL_NOT_ALLOWED"
  | "COMMENT_CONTROL_CHARACTER"
  | "COMMENT_SPAM_PATTERN"
  | "REACTION_SUBJECT_REQUIRED"
  | "REACTION_UNAVAILABLE"
  | "REPORT_SUBJECT_REQUIRED"
  | "REPORT_UNAVAILABLE"
  | "REPORT_OWN_COMMENT"
  | "REPORT_ALREADY_EXISTS"
  | "REPORT_RATE_LIMITED"
  | "REPORT_DETAIL_REQUIRED"
  | "REPORT_DETAIL_NOT_ALLOWED"
  | "MODERATION_AUTH_REQUIRED"
  | "MODERATION_COMMENT_NOT_FOUND";

export class CommentError extends Error {
  constructor(
    public readonly code: CommentErrorCode,
    public readonly statusCode: 400 | 401 | 403 | 404 | 409 | 422 | 429,
    message: string,
  ) {
    super(message);
    this.name = "CommentError";
  }
}

export { CommentError as CommentReadError };
