// Channel addresses supplied in the 2026-09-19 handoff; no live collection has been verified.
export const POLL_CHANNEL_REGISTER = [
  {
    name: "진행빵집",
    channelId: null,
    channelUrl: "https://www.youtube.com/@jinhaeng_bakery",
    communityUrl: "https://www.youtube.com/@jinhaeng_bakery/community",
    initialBatchEligible: true,
    identityNeedsConfirmation: false,
    liveCollectionVerified: false,
  },
  {
    name: "뭉케뭉케",
    channelId: "UCun14pE-GmXEd1qB9FLuQHA",
    channelUrl: "https://www.youtube.com/@뭉케",
    communityUrl: "https://www.youtube.com/@%EB%AD%89%EC%BC%80/community",
    initialBatchEligible: true,
    identityNeedsConfirmation: false,
    liveCollectionVerified: false,
  },
  {
    name: "궁금해소",
    channelId: null,
    channelUrl: "https://www.youtube.com/@whysolution",
    communityUrl: "https://www.youtube.com/@whysolution/community",
    initialBatchEligible: true,
    identityNeedsConfirmation: false,
    liveCollectionVerified: false,
  },
  {
    name: "만렙백수",
    channelId: "UCn8tvVLoVaPP4MjDwMff5MA",
    channelUrl: "https://www.youtube.com/channel/UCn8tvVLoVaPP4MjDwMff5MA",
    communityUrl: "https://www.youtube.com/channel/UCn8tvVLoVaPP4MjDwMff5MA/community",
    initialBatchEligible: false,
    identityNeedsConfirmation: true,
    liveCollectionVerified: false,
  },
  {
    name: "그분이 알고싶다",
    channelId: null,
    channelUrl: "https://www.youtube.com/@그분이알고싶다",
    communityUrl:
      "https://www.youtube.com/@%EA%B7%B8%EB%B6%84%EC%9D%B4%EC%95%8C%EA%B3%A0%EC%8B%B6%EB%8B%A4/community",
    initialBatchEligible: true,
    identityNeedsConfirmation: false,
    liveCollectionVerified: false,
  },
  {
    name: "주식초등학교",
    channelId: "UCaQREsefLy-W8ruWcJ7IDtg",
    channelUrl: "https://www.youtube.com/@joosik_school",
    communityUrl: "https://www.youtube.com/@joosik_school/community",
    initialBatchEligible: true,
    identityNeedsConfirmation: false,
    liveCollectionVerified: false,
  },
  {
    name: "경제야놀자",
    channelId: "UCgjsiInAgdceEq2lpRNNYvw",
    channelUrl: "https://www.youtube.com/channel/UCgjsiInAgdceEq2lpRNNYvw",
    communityUrl: "https://www.youtube.com/channel/UCgjsiInAgdceEq2lpRNNYvw/community",
    initialBatchEligible: true,
    identityNeedsConfirmation: false,
    liveCollectionVerified: false,
  },
  {
    name: "가비 걸",
    channelId: null,
    channelUrl: "https://www.youtube.com/@GABEEGIRL",
    communityUrl: "https://www.youtube.com/@GABEEGIRL/community",
    initialBatchEligible: true,
    identityNeedsConfirmation: false,
    liveCollectionVerified: false,
  },
  {
    name: "짤툰",
    channelId: "UCszFjh7CEfwDb7UUGb4RzCQ",
    channelUrl: "https://www.youtube.com/@jjaltoon",
    communityUrl: "https://www.youtube.com/@jjaltoon/community",
    initialBatchEligible: true,
    identityNeedsConfirmation: false,
    liveCollectionVerified: false,
  },
  {
    name: "쩝쩝박사",
    channelId: "UC6M527IbybtNOn9D6IAOEyQ",
    channelUrl: "https://www.youtube.com/@쩝쩝박사v",
    communityUrl: "https://www.youtube.com/@%EC%A9%9D%EC%A9%9D%EB%B0%95%EC%82%ACv/community",
    initialBatchEligible: true,
    identityNeedsConfirmation: false,
    liveCollectionVerified: false,
  },
  {
    name: "닥터딩요",
    channelId: null,
    channelUrl: "https://www.youtube.com/@doctordinho",
    communityUrl: "https://www.youtube.com/@doctordinho/community",
    initialBatchEligible: true,
    identityNeedsConfirmation: false,
    liveCollectionVerified: false,
  },
  {
    name: "캠핑한끼CampingHankki",
    channelId: null,
    channelUrl: "https://www.youtube.com/@campinghankki",
    communityUrl: "https://www.youtube.com/@campinghankki/community",
    initialBatchEligible: true,
    identityNeedsConfirmation: false,
    liveCollectionVerified: false,
  },
] as const;
